name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # GitHub Pagesにデプロイしたいブランチ

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをクローン
      - name: Checkout repository
        uses: actions/checkout@v2

      # Node.jsをセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Firebase設定を環境変数として設定
      - name: Set Firebase environment variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV

      # Firebase設定を埋め込むためにビルド
      - name: Build project
        run: |
          sed -i "s/API_KEY/${{ secrets.FIREBASE_API_KEY }}/g" src/app.js
          sed -i "s/AUTH_DOMAIN/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" src/app.js
          sed -i "s/PROJECT_ID/${{ secrets.FIREBASE_PROJECT_ID }}/g" src/app.js
          sed -i "s/STORAGE_BUCKET/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" src/app.js
          sed -i "s/MESSAGING_SENDER_ID/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" src/app.js
          sed -i "s/APP_ID/${{ secrets.FIREBASE_APP_ID }}/g" src/app.js
          sed -i "s/MEASUREMENT_ID/${{ secrets.FIREBASE_MEASUREMENT_ID }}/g" src/app.js

      # GitHub Pagesへデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # 出力先ディレクトリ
